#!/usr/bin/env python3
"""
group_nodes.py

Description
-----------
This script parses an IR JSON file (ir.json) generated by the IR tracing tool
and groups nodes according to the compiler phase in which they were created.

Each node contains an `instAccess` log that records instructions interacting
with the node. A node creation is represented by an access entry with:

    type = 7  (CREATE)

Each access entry also contains a `PhaseFnId` field that identifies the
compiler phase responsible for the event. This script extracts the PhaseFnId
from the CREATE event of each node and groups nodes by that phase.

The phase name is resolved using the `fnId2Name` table stored in the JSON file.

Output Format
-------------
The script prints one line per phase:

    PhaseName: [node_id_1, node_id_2, ...]

Example:

    v8::internal::compiler::GraphBuilderPhase::Run: [1, 2, 3, 4]
    v8::internal::compiler::InliningPhase::Run: [5, 6]

Requirements
------------
Python 3.x

Usage
-----
Run the script from the command line:

    python3 group_nodes.py ir.json

Where:

    ir.json   JSON file produced by the IR tracing tool.

Error Checking
--------------
The script asserts the following conditions:

1. Every node must contain an `instAccess` log.
2. Every node must contain a CREATE event (`type == 7`).
3. Every CREATE event must include a valid `PhaseFnId`.

If any of these conditions fail, the script terminates with an assertion error.

Author: Terrence Lim (with the help of LLM).
"""

import json
import sys
from collections import defaultdict

# Access type constant representing node creation
CREATE = 7


def load_json(path):
    """
    Load and parse a JSON file.

    Parameters
    ----------
    path : str
        Path to the JSON file.

    Returns
    -------
    dict
        Parsed JSON object.
    """
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def get_creation_phase_fnid(node):
    """
    Determine the compiler phase in which a node was created.

    The function inspects the `instAccess` entries of a node and finds
    the first instruction whose access type is CREATE (type 7).
    The PhaseFnId associated with that event identifies the phase.

    Parameters
    ----------
    node : dict
        JSON object representing a node.

    Returns
    -------
    int
        PhaseFnId corresponding to the node creation phase.

    Raises
    ------
    AssertionError
        If the node does not contain a CREATE event or instAccess entries.
    """

    inst_access = node.get("instAccess", {})
    node_id = node.get("id")

    # Ensure the node contains access records
    assert inst_access, f"Node {node_id} has empty instAccess."

    # Instruction IDs are stored as strings in JSON
    # Sort them numerically to reconstruct execution order
    sorted_items = sorted(inst_access.items(), key=lambda x: int(x[0]))

    create_event = None

    # Search for the CREATE event
    for inst_id, event in sorted_items:
        if event.get("type") == CREATE:
            create_event = event
            break

    # Ensure a CREATE event exists
    assert create_event is not None, \
            f"Node {node_id} has no CREATE (type 7) instruction."

    phase_fnid = create_event.get("PhaseFnId")

    # Ensure PhaseFnId is present
    assert phase_fnid is not None, \
            f"Node {node_id} CREATE event missing PhaseFnId."

    return phase_fnid


def group_nodes_by_creation_phase(data):
    """
    Group nodes by the compiler phase in which they were created.

    Parameters
    ----------
    data : dict
        Parsed JSON object representing the entire IR dataset.

    Returns
    -------
    tuple
        (phase_to_nodes, fnid_to_name)

        phase_to_nodes : dict
            Mapping from PhaseFnId to list of node IDs.

        fnid_to_name : dict
            Mapping from function ID to function name.
    """

    fnid_to_name = data.get("fnId2Name", {})
    phase_to_nodes = defaultdict(list)

    # Iterate through all nodes in the dataset
    for node in data.get("nodes", []):
        node_id = node.get("id")

        # Determine which phase created the node
        phase_fnid = get_creation_phase_fnid(node)

        # Add the node to the corresponding phase group
        phase_to_nodes[phase_fnid].append(node_id)

    return phase_to_nodes, fnid_to_name


def main():
    """
    Main program entry point.

    This function:

    1. Parses command line arguments.
    2. Loads the JSON dataset.
    3. Groups nodes by creation phase.
    4. Prints grouped results.
    """

    # Ensure the user provided the JSON file
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <ir.json>")
        sys.exit(1)

    json_path = sys.argv[1]

    # Load JSON dataset
    data = load_json(json_path)

    # Group nodes by phase
    phase_to_nodes, fnid_to_name = group_nodes_by_creation_phase(data)

    # Print grouped results
    for phase_fnid in sorted(phase_to_nodes.keys(), key=lambda x: int(x)):
        phase_name = fnid_to_name.get(str(phase_fnid),
                f"<unknown phase name: {phase_fnid}>")

        node_ids = sorted(phase_to_nodes[phase_fnid])

        print(f"{phase_name}: {node_ids}")


if __name__ == "__main__":
    main()
