"""
    Json2PythonObj.py
    This program reads in the IR JSON file generated by the IRModeler,
    and generates a new IR python object.

    Input:
    Output:

    How to use?
    $
"""

import sys

from IR import IRGraph
from IR import Node

def Json2PythonObj(irDict: dict):

    IRGraph = IRGraph()
