#include "PinLynxReg.h"

const REG LynxReg2RegArr[] = {
#ifdef TARGET_IA32
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_SEG_CS,
	LEVEL_BASE::REG_SEG_DS,
	LEVEL_BASE::REG_SEG_ES,
	LEVEL_BASE::REG_SEG_FS_BASE,
	LEVEL_BASE::REG_SEG_GS,
	LEVEL_BASE::REG_SEG_SS,
	LEVEL_BASE::REG_MXCSR,
	LEVEL_BASE::REG_ST0,
	LEVEL_BASE::REG_ST1,
	LEVEL_BASE::REG_ST2,
	LEVEL_BASE::REG_ST3,
	LEVEL_BASE::REG_ST4,
	LEVEL_BASE::REG_ST5,
	LEVEL_BASE::REG_ST6,
	LEVEL_BASE::REG_ST7,
	LEVEL_BASE::REG_FPSW,
	LEVEL_BASE::REG_FPCW,
	#ifdef REG_FPTAG_FULL
	LEVEL_BASE::REG_FPTAG_FULL,
#else
	LEVEL_BASE::REG_INVALID_,
#endif
	LEVEL_BASE::REG_FPIP_OFF,
	LEVEL_BASE::REG_FPIP_SEL,
	LEVEL_BASE::REG_FPDP_OFF,
	LEVEL_BASE::REG_FPDP_SEL,
	LEVEL_BASE::REG_FPOPCODE,
	LEVEL_BASE::REG_DR0,
	LEVEL_BASE::REG_DR1,
	LEVEL_BASE::REG_DR2,
	LEVEL_BASE::REG_DR3,
	LEVEL_BASE::REG_DR4,
	LEVEL_BASE::REG_DR5,
	LEVEL_BASE::REG_DR6,
	LEVEL_BASE::REG_DR7,
	LEVEL_BASE::REG_CR0,
	LEVEL_BASE::REG_CR1,
	LEVEL_BASE::REG_CR2,
	LEVEL_BASE::REG_CR3,
	LEVEL_BASE::REG_CR4,
	LEVEL_BASE::REG_GFLAGS,
	LEVEL_BASE::REG_YMM0,
	LEVEL_BASE::REG_YMM1,
	LEVEL_BASE::REG_YMM2,
	LEVEL_BASE::REG_YMM3,
	LEVEL_BASE::REG_YMM4,
	LEVEL_BASE::REG_YMM5,
	LEVEL_BASE::REG_YMM6,
	LEVEL_BASE::REG_YMM7,
	LEVEL_BASE::REG_EIP,
	LEVEL_BASE::REG_EAX,
	LEVEL_BASE::REG_EBX,
	LEVEL_BASE::REG_ECX,
	LEVEL_BASE::REG_EDX,
	LEVEL_BASE::REG_EBP,
	LEVEL_BASE::REG_ESI,
	LEVEL_BASE::REG_EDI,
	LEVEL_BASE::REG_ESP,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_IP,
	LEVEL_BASE::REG_AX,
	LEVEL_BASE::REG_BX,
	LEVEL_BASE::REG_CX,
	LEVEL_BASE::REG_DX,
	LEVEL_BASE::REG_BP,
	LEVEL_BASE::REG_SI,
	LEVEL_BASE::REG_DI,
	LEVEL_BASE::REG_SP,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_AH,
	LEVEL_BASE::REG_BH,
	LEVEL_BASE::REG_CH,
	LEVEL_BASE::REG_DH,
	LEVEL_BASE::REG_AL,
	LEVEL_BASE::REG_BL,
	LEVEL_BASE::REG_CL,
	LEVEL_BASE::REG_DL,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_XMM0,
	LEVEL_BASE::REG_XMM1,
	LEVEL_BASE::REG_XMM2,
	LEVEL_BASE::REG_XMM3,
	LEVEL_BASE::REG_XMM4,
	LEVEL_BASE::REG_XMM5,
	LEVEL_BASE::REG_XMM6,
	LEVEL_BASE::REG_XMM7,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_MM0,
	LEVEL_BASE::REG_MM1,
	LEVEL_BASE::REG_MM2,
	LEVEL_BASE::REG_MM3,
	LEVEL_BASE::REG_MM4,
	LEVEL_BASE::REG_MM5,
	LEVEL_BASE::REG_MM6,
	LEVEL_BASE::REG_MM7,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
#endif
#ifdef TARGET_IA32E
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_RIP,
	LEVEL_BASE::REG_RAX,
	LEVEL_BASE::REG_RBX,
	LEVEL_BASE::REG_RCX,
	LEVEL_BASE::REG_RDX,
	LEVEL_BASE::REG_RBP,
	LEVEL_BASE::REG_RSI,
	LEVEL_BASE::REG_RDI,
	LEVEL_BASE::REG_RSP,
	LEVEL_BASE::REG_R8,
	LEVEL_BASE::REG_R9,
	LEVEL_BASE::REG_R10,
	LEVEL_BASE::REG_R11,
	LEVEL_BASE::REG_R12,
	LEVEL_BASE::REG_R13,
	LEVEL_BASE::REG_R14,
	LEVEL_BASE::REG_R15,
	LEVEL_BASE::REG_SEG_CS,
	LEVEL_BASE::REG_SEG_DS,
	LEVEL_BASE::REG_SEG_ES,
	LEVEL_BASE::REG_SEG_FS_BASE,
	LEVEL_BASE::REG_SEG_GS,
	LEVEL_BASE::REG_SEG_SS,
	LEVEL_BASE::REG_MXCSR,
	LEVEL_BASE::REG_ST0,
	LEVEL_BASE::REG_ST1,
	LEVEL_BASE::REG_ST2,
	LEVEL_BASE::REG_ST3,
	LEVEL_BASE::REG_ST4,
	LEVEL_BASE::REG_ST5,
	LEVEL_BASE::REG_ST6,
	LEVEL_BASE::REG_ST7,
	LEVEL_BASE::REG_FPSW,
	LEVEL_BASE::REG_FPCW,
	#ifdef REG_FPTAG_FULL
	LEVEL_BASE::REG_FPTAG_FULL,
#else
	LEVEL_BASE::REG_INVALID_,
#endif
	LEVEL_BASE::REG_FPIP_OFF,
	LEVEL_BASE::REG_FPIP_SEL,
	LEVEL_BASE::REG_FPDP_OFF,
	LEVEL_BASE::REG_FPDP_SEL,
	LEVEL_BASE::REG_FPOPCODE,
	LEVEL_BASE::REG_DR0,
	LEVEL_BASE::REG_DR1,
	LEVEL_BASE::REG_DR2,
	LEVEL_BASE::REG_DR3,
	LEVEL_BASE::REG_DR4,
	LEVEL_BASE::REG_DR5,
	LEVEL_BASE::REG_DR6,
	LEVEL_BASE::REG_DR7,
	LEVEL_BASE::REG_CR0,
	LEVEL_BASE::REG_CR1,
	LEVEL_BASE::REG_CR2,
	LEVEL_BASE::REG_CR3,
	LEVEL_BASE::REG_CR4,
	LEVEL_BASE::REG_GFLAGS,
	LEVEL_BASE::REG_YMM0,
	LEVEL_BASE::REG_YMM1,
	LEVEL_BASE::REG_YMM2,
	LEVEL_BASE::REG_YMM3,
	LEVEL_BASE::REG_YMM4,
	LEVEL_BASE::REG_YMM5,
	LEVEL_BASE::REG_YMM6,
	LEVEL_BASE::REG_YMM7,
	LEVEL_BASE::REG_EIP,
	LEVEL_BASE::REG_EAX,
	LEVEL_BASE::REG_EBX,
	LEVEL_BASE::REG_ECX,
	LEVEL_BASE::REG_EDX,
	LEVEL_BASE::REG_EBP,
	LEVEL_BASE::REG_ESI,
	LEVEL_BASE::REG_EDI,
	LEVEL_BASE::REG_ESP,
	LEVEL_BASE::REG_R8D,
	LEVEL_BASE::REG_R9D,
	LEVEL_BASE::REG_R10D,
	LEVEL_BASE::REG_R11D,
	LEVEL_BASE::REG_R12D,
	LEVEL_BASE::REG_R13D,
	LEVEL_BASE::REG_R14D,
	LEVEL_BASE::REG_R15D,
	LEVEL_BASE::REG_IP,
	LEVEL_BASE::REG_AX,
	LEVEL_BASE::REG_BX,
	LEVEL_BASE::REG_CX,
	LEVEL_BASE::REG_DX,
	LEVEL_BASE::REG_BP,
	LEVEL_BASE::REG_SI,
	LEVEL_BASE::REG_DI,
	LEVEL_BASE::REG_SP,
	LEVEL_BASE::REG_R8W,
	LEVEL_BASE::REG_R9W,
	LEVEL_BASE::REG_R10W,
	LEVEL_BASE::REG_R11W,
	LEVEL_BASE::REG_R12W,
	LEVEL_BASE::REG_R13W,
	LEVEL_BASE::REG_R14W,
	LEVEL_BASE::REG_R15W,
	LEVEL_BASE::REG_AH,
	LEVEL_BASE::REG_BH,
	LEVEL_BASE::REG_CH,
	LEVEL_BASE::REG_DH,
	LEVEL_BASE::REG_AL,
	LEVEL_BASE::REG_BL,
	LEVEL_BASE::REG_CL,
	LEVEL_BASE::REG_DL,
	LEVEL_BASE::REG_BPL,
	LEVEL_BASE::REG_SIL,
	LEVEL_BASE::REG_DIL,
	LEVEL_BASE::REG_SPL,
	LEVEL_BASE::REG_R8B,
	LEVEL_BASE::REG_R9B,
	LEVEL_BASE::REG_R10B,
	LEVEL_BASE::REG_R11B,
	LEVEL_BASE::REG_R12B,
	LEVEL_BASE::REG_R13B,
	LEVEL_BASE::REG_R14B,
	LEVEL_BASE::REG_R15B,
	LEVEL_BASE::REG_YMM8,
	LEVEL_BASE::REG_YMM9,
	LEVEL_BASE::REG_YMM10,
	LEVEL_BASE::REG_YMM11,
	LEVEL_BASE::REG_YMM12,
	LEVEL_BASE::REG_YMM13,
	LEVEL_BASE::REG_YMM14,
	LEVEL_BASE::REG_YMM15,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_XMM0,
	LEVEL_BASE::REG_XMM1,
	LEVEL_BASE::REG_XMM2,
	LEVEL_BASE::REG_XMM3,
	LEVEL_BASE::REG_XMM4,
	LEVEL_BASE::REG_XMM5,
	LEVEL_BASE::REG_XMM6,
	LEVEL_BASE::REG_XMM7,
	LEVEL_BASE::REG_XMM8,
	LEVEL_BASE::REG_XMM9,
	LEVEL_BASE::REG_XMM10,
	LEVEL_BASE::REG_XMM11,
	LEVEL_BASE::REG_XMM12,
	LEVEL_BASE::REG_XMM13,
	LEVEL_BASE::REG_XMM14,
	LEVEL_BASE::REG_XMM15,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_MM0,
	LEVEL_BASE::REG_MM1,
	LEVEL_BASE::REG_MM2,
	LEVEL_BASE::REG_MM3,
	LEVEL_BASE::REG_MM4,
	LEVEL_BASE::REG_MM5,
	LEVEL_BASE::REG_MM6,
	LEVEL_BASE::REG_MM7,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
#endif
#ifdef TARGET_MIC
	LEVEL_BASE::REG_ZMM0,
	LEVEL_BASE::REG_ZMM1,
	LEVEL_BASE::REG_ZMM2,
	LEVEL_BASE::REG_ZMM3,
	LEVEL_BASE::REG_ZMM4,
	LEVEL_BASE::REG_ZMM5,
	LEVEL_BASE::REG_ZMM6,
	LEVEL_BASE::REG_ZMM7,
	LEVEL_BASE::REG_ZMM8,
	LEVEL_BASE::REG_ZMM9,
	LEVEL_BASE::REG_ZMM10,
	LEVEL_BASE::REG_ZMM11,
	LEVEL_BASE::REG_ZMM12,
	LEVEL_BASE::REG_ZMM13,
	LEVEL_BASE::REG_ZMM14,
	LEVEL_BASE::REG_ZMM15,
	LEVEL_BASE::REG_ZMM16,
	LEVEL_BASE::REG_ZMM17,
	LEVEL_BASE::REG_ZMM18,
	LEVEL_BASE::REG_ZMM19,
	LEVEL_BASE::REG_ZMM20,
	LEVEL_BASE::REG_ZMM21,
	LEVEL_BASE::REG_ZMM22,
	LEVEL_BASE::REG_ZMM23,
	LEVEL_BASE::REG_ZMM24,
	LEVEL_BASE::REG_ZMM25,
	LEVEL_BASE::REG_ZMM26,
	LEVEL_BASE::REG_ZMM27,
	LEVEL_BASE::REG_ZMM28,
	LEVEL_BASE::REG_ZMM29,
	LEVEL_BASE::REG_ZMM30,
	LEVEL_BASE::REG_ZMM31,
	LEVEL_BASE::REG_K0,
	LEVEL_BASE::REG_K1,
	LEVEL_BASE::REG_K2,
	LEVEL_BASE::REG_K3,
	LEVEL_BASE::REG_K4,
	LEVEL_BASE::REG_K5,
	LEVEL_BASE::REG_K6,
	LEVEL_BASE::REG_K7,
	LEVEL_BASE::REG_RIP,
	LEVEL_BASE::REG_RAX,
	LEVEL_BASE::REG_RBX,
	LEVEL_BASE::REG_RCX,
	LEVEL_BASE::REG_RDX,
	LEVEL_BASE::REG_RBP,
	LEVEL_BASE::REG_RSI,
	LEVEL_BASE::REG_RDI,
	LEVEL_BASE::REG_RSP,
	LEVEL_BASE::REG_R8,
	LEVEL_BASE::REG_R9,
	LEVEL_BASE::REG_R10,
	LEVEL_BASE::REG_R11,
	LEVEL_BASE::REG_R12,
	LEVEL_BASE::REG_R13,
	LEVEL_BASE::REG_R14,
	LEVEL_BASE::REG_R15,
	LEVEL_BASE::REG_SEG_CS,
	LEVEL_BASE::REG_SEG_DS,
	LEVEL_BASE::REG_SEG_ES,
	LEVEL_BASE::REG_SEG_FS_BASE,
	LEVEL_BASE::REG_SEG_GS,
	LEVEL_BASE::REG_SEG_SS,
	LEVEL_BASE::REG_MXCSR,
	LEVEL_BASE::REG_ST0,
	LEVEL_BASE::REG_ST1,
	LEVEL_BASE::REG_ST2,
	LEVEL_BASE::REG_ST3,
	LEVEL_BASE::REG_ST4,
	LEVEL_BASE::REG_ST5,
	LEVEL_BASE::REG_ST6,
	LEVEL_BASE::REG_ST7,
	LEVEL_BASE::REG_FPSW,
	LEVEL_BASE::REG_FPCW,
	#ifdef REG_FPTAG_FULL
	LEVEL_BASE::REG_FPTAG_FULL,
#else
	LEVEL_BASE::REG_INVALID_,
#endif
	LEVEL_BASE::REG_FPIP_OFF,
	LEVEL_BASE::REG_FPIP_SEL,
	LEVEL_BASE::REG_FPDP_OFF,
	LEVEL_BASE::REG_FPDP_SEL,
	LEVEL_BASE::REG_FPOPCODE,
	LEVEL_BASE::REG_DR0,
	LEVEL_BASE::REG_DR1,
	LEVEL_BASE::REG_DR2,
	LEVEL_BASE::REG_DR3,
	LEVEL_BASE::REG_DR4,
	LEVEL_BASE::REG_DR5,
	LEVEL_BASE::REG_DR6,
	LEVEL_BASE::REG_DR7,
	LEVEL_BASE::REG_CR0,
	LEVEL_BASE::REG_CR1,
	LEVEL_BASE::REG_CR2,
	LEVEL_BASE::REG_CR3,
	LEVEL_BASE::REG_CR4,
	LEVEL_BASE::REG_GFLAGS,
	LEVEL_BASE::REG_YMM0,
	LEVEL_BASE::REG_YMM1,
	LEVEL_BASE::REG_YMM2,
	LEVEL_BASE::REG_YMM3,
	LEVEL_BASE::REG_YMM4,
	LEVEL_BASE::REG_YMM5,
	LEVEL_BASE::REG_YMM6,
	LEVEL_BASE::REG_YMM7,
	LEVEL_BASE::REG_EIP,
	LEVEL_BASE::REG_EAX,
	LEVEL_BASE::REG_EBX,
	LEVEL_BASE::REG_ECX,
	LEVEL_BASE::REG_EDX,
	LEVEL_BASE::REG_EBP,
	LEVEL_BASE::REG_ESI,
	LEVEL_BASE::REG_EDI,
	LEVEL_BASE::REG_ESP,
	LEVEL_BASE::REG_R8D,
	LEVEL_BASE::REG_R9D,
	LEVEL_BASE::REG_R10D,
	LEVEL_BASE::REG_R11D,
	LEVEL_BASE::REG_R12D,
	LEVEL_BASE::REG_R13D,
	LEVEL_BASE::REG_R14D,
	LEVEL_BASE::REG_R15D,
	LEVEL_BASE::REG_IP,
	LEVEL_BASE::REG_AX,
	LEVEL_BASE::REG_BX,
	LEVEL_BASE::REG_CX,
	LEVEL_BASE::REG_DX,
	LEVEL_BASE::REG_BP,
	LEVEL_BASE::REG_SI,
	LEVEL_BASE::REG_DI,
	LEVEL_BASE::REG_SP,
	LEVEL_BASE::REG_R8W,
	LEVEL_BASE::REG_R9W,
	LEVEL_BASE::REG_R10W,
	LEVEL_BASE::REG_R11W,
	LEVEL_BASE::REG_R12W,
	LEVEL_BASE::REG_R13W,
	LEVEL_BASE::REG_R14W,
	LEVEL_BASE::REG_R15W,
	LEVEL_BASE::REG_AH,
	LEVEL_BASE::REG_BH,
	LEVEL_BASE::REG_CH,
	LEVEL_BASE::REG_DH,
	LEVEL_BASE::REG_AL,
	LEVEL_BASE::REG_BL,
	LEVEL_BASE::REG_CL,
	LEVEL_BASE::REG_DL,
	LEVEL_BASE::REG_BPL,
	LEVEL_BASE::REG_SIL,
	LEVEL_BASE::REG_DIL,
	LEVEL_BASE::REG_SPL,
	LEVEL_BASE::REG_R8B,
	LEVEL_BASE::REG_R9B,
	LEVEL_BASE::REG_R10B,
	LEVEL_BASE::REG_R11B,
	LEVEL_BASE::REG_R12B,
	LEVEL_BASE::REG_R13B,
	LEVEL_BASE::REG_R14B,
	LEVEL_BASE::REG_R15B,
	LEVEL_BASE::REG_YMM8,
	LEVEL_BASE::REG_YMM9,
	LEVEL_BASE::REG_YMM10,
	LEVEL_BASE::REG_YMM11,
	LEVEL_BASE::REG_YMM12,
	LEVEL_BASE::REG_YMM13,
	LEVEL_BASE::REG_YMM14,
	LEVEL_BASE::REG_YMM15,
	LEVEL_BASE::REG_YMM16,
	LEVEL_BASE::REG_YMM17,
	LEVEL_BASE::REG_YMM18,
	LEVEL_BASE::REG_YMM19,
	LEVEL_BASE::REG_YMM20,
	LEVEL_BASE::REG_YMM21,
	LEVEL_BASE::REG_YMM22,
	LEVEL_BASE::REG_YMM23,
	LEVEL_BASE::REG_YMM24,
	LEVEL_BASE::REG_YMM25,
	LEVEL_BASE::REG_YMM26,
	LEVEL_BASE::REG_YMM27,
	LEVEL_BASE::REG_YMM28,
	LEVEL_BASE::REG_YMM29,
	LEVEL_BASE::REG_YMM30,
	LEVEL_BASE::REG_YMM31,
	LEVEL_BASE::REG_XMM0,
	LEVEL_BASE::REG_XMM1,
	LEVEL_BASE::REG_XMM2,
	LEVEL_BASE::REG_XMM3,
	LEVEL_BASE::REG_XMM4,
	LEVEL_BASE::REG_XMM5,
	LEVEL_BASE::REG_XMM6,
	LEVEL_BASE::REG_XMM7,
	LEVEL_BASE::REG_XMM8,
	LEVEL_BASE::REG_XMM9,
	LEVEL_BASE::REG_XMM10,
	LEVEL_BASE::REG_XMM11,
	LEVEL_BASE::REG_XMM12,
	LEVEL_BASE::REG_XMM13,
	LEVEL_BASE::REG_XMM14,
	LEVEL_BASE::REG_XMM15,
	LEVEL_BASE::REG_XMM16,
	LEVEL_BASE::REG_XMM17,
	LEVEL_BASE::REG_XMM18,
	LEVEL_BASE::REG_XMM19,
	LEVEL_BASE::REG_XMM20,
	LEVEL_BASE::REG_XMM21,
	LEVEL_BASE::REG_XMM22,
	LEVEL_BASE::REG_XMM23,
	LEVEL_BASE::REG_XMM24,
	LEVEL_BASE::REG_XMM25,
	LEVEL_BASE::REG_XMM26,
	LEVEL_BASE::REG_XMM27,
	LEVEL_BASE::REG_XMM28,
	LEVEL_BASE::REG_XMM29,
	LEVEL_BASE::REG_XMM30,
	LEVEL_BASE::REG_XMM31,
	LEVEL_BASE::REG_MM0,
	LEVEL_BASE::REG_MM1,
	LEVEL_BASE::REG_MM2,
	LEVEL_BASE::REG_MM3,
	LEVEL_BASE::REG_MM4,
	LEVEL_BASE::REG_MM5,
	LEVEL_BASE::REG_MM6,
	LEVEL_BASE::REG_MM7,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
#endif
#ifdef TARGET_NONE
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_INVALID_,
	LEVEL_BASE::REG_FPU_STACK,
	LEVEL_BASE::REG_INVALID_,
#endif
};
REG LynxReg2Reg(LynxReg lReg) {
	return LynxReg2RegArr[lReg];
}
LynxReg Reg2LynxReg(REG reg) {
	switch(reg) {
#ifdef TARGET_IA32
		case LEVEL_BASE::REG_SEG_CS:
			return LYNX_SEG_CS;
		case LEVEL_BASE::REG_SEG_DS:
			return LYNX_SEG_DS;
		case LEVEL_BASE::REG_SEG_ES:
			return LYNX_SEG_ES;
        case LEVEL_BASE::REG_SEG_FS_BASE:
		case LEVEL_BASE::REG_SEG_FS:
			return LYNX_SEG_FS;
		case LEVEL_BASE::REG_SEG_GS:
			return LYNX_SEG_GS;
		case LEVEL_BASE::REG_SEG_SS:
			return LYNX_SEG_SS;
		case LEVEL_BASE::REG_MXCSR:
			return LYNX_MXCSR;
		case LEVEL_BASE::REG_ST0:
			return LYNX_ST0;
		case LEVEL_BASE::REG_ST1:
			return LYNX_ST1;
		case LEVEL_BASE::REG_ST2:
			return LYNX_ST2;
		case LEVEL_BASE::REG_ST3:
			return LYNX_ST3;
		case LEVEL_BASE::REG_ST4:
			return LYNX_ST4;
		case LEVEL_BASE::REG_ST5:
			return LYNX_ST5;
		case LEVEL_BASE::REG_ST6:
			return LYNX_ST6;
		case LEVEL_BASE::REG_ST7:
			return LYNX_ST7;
		case LEVEL_BASE::REG_FPSW:
			return LYNX_FPSW;
		case LEVEL_BASE::REG_FPCW:
			return LYNX_FPCW;
		#ifdef REG_FPTAG_FULL
		case LEVEL_BASE::REG_FPTAG_FULL:
			return LYNX_FPTAG_FULL;
#endif
			return LYNX_FPTAG_FULL;
		case LEVEL_BASE::REG_FPIP_OFF:
			return LYNX_FPIP_OFF;
		case LEVEL_BASE::REG_FPIP_SEL:
			return LYNX_FPIP_SEL;
		case LEVEL_BASE::REG_FPDP_OFF:
			return LYNX_FPDP_OFF;
		case LEVEL_BASE::REG_FPDP_SEL:
			return LYNX_FPDP_SEL;
		case LEVEL_BASE::REG_FPOPCODE:
			return LYNX_FPOPCODE;
		case LEVEL_BASE::REG_DR0:
			return LYNX_DR0;
		case LEVEL_BASE::REG_DR1:
			return LYNX_DR1;
		case LEVEL_BASE::REG_DR2:
			return LYNX_DR2;
		case LEVEL_BASE::REG_DR3:
			return LYNX_DR3;
		case LEVEL_BASE::REG_DR4:
			return LYNX_DR4;
		case LEVEL_BASE::REG_DR5:
			return LYNX_DR5;
		case LEVEL_BASE::REG_DR6:
			return LYNX_DR6;
		case LEVEL_BASE::REG_DR7:
			return LYNX_DR7;
		case LEVEL_BASE::REG_CR0:
			return LYNX_CR0;
		case LEVEL_BASE::REG_CR1:
			return LYNX_CR1;
		case LEVEL_BASE::REG_CR2:
			return LYNX_CR2;
		case LEVEL_BASE::REG_CR3:
			return LYNX_CR3;
		case LEVEL_BASE::REG_CR4:
			return LYNX_CR4;
		case LEVEL_BASE::REG_GFLAGS:
			return LYNX_GFLAGS;
		case LEVEL_BASE::REG_YMM0:
			return LYNX_YMM0;
		case LEVEL_BASE::REG_YMM1:
			return LYNX_YMM1;
		case LEVEL_BASE::REG_YMM2:
			return LYNX_YMM2;
		case LEVEL_BASE::REG_YMM3:
			return LYNX_YMM3;
		case LEVEL_BASE::REG_YMM4:
			return LYNX_YMM4;
		case LEVEL_BASE::REG_YMM5:
			return LYNX_YMM5;
		case LEVEL_BASE::REG_YMM6:
			return LYNX_YMM6;
		case LEVEL_BASE::REG_YMM7:
			return LYNX_YMM7;
		case LEVEL_BASE::REG_EIP:
			return LYNX_EIP;
		case LEVEL_BASE::REG_EAX:
			return LYNX_EAX;
		case LEVEL_BASE::REG_EBX:
			return LYNX_EBX;
		case LEVEL_BASE::REG_ECX:
			return LYNX_ECX;
		case LEVEL_BASE::REG_EDX:
			return LYNX_EDX;
		case LEVEL_BASE::REG_EBP:
			return LYNX_EBP;
		case LEVEL_BASE::REG_ESI:
			return LYNX_ESI;
		case LEVEL_BASE::REG_EDI:
			return LYNX_EDI;
		case LEVEL_BASE::REG_ESP:
			return LYNX_ESP;
		case LEVEL_BASE::REG_IP:
			return LYNX_IP;
		case LEVEL_BASE::REG_AX:
			return LYNX_AX;
		case LEVEL_BASE::REG_BX:
			return LYNX_BX;
		case LEVEL_BASE::REG_CX:
			return LYNX_CX;
		case LEVEL_BASE::REG_DX:
			return LYNX_DX;
		case LEVEL_BASE::REG_BP:
			return LYNX_BP;
		case LEVEL_BASE::REG_SI:
			return LYNX_SI;
		case LEVEL_BASE::REG_DI:
			return LYNX_DI;
		case LEVEL_BASE::REG_SP:
			return LYNX_SP;
		case LEVEL_BASE::REG_AH:
			return LYNX_AH;
		case LEVEL_BASE::REG_BH:
			return LYNX_BH;
		case LEVEL_BASE::REG_CH:
			return LYNX_CH;
		case LEVEL_BASE::REG_DH:
			return LYNX_DH;
		case LEVEL_BASE::REG_AL:
			return LYNX_AL;
		case LEVEL_BASE::REG_BL:
			return LYNX_BL;
		case LEVEL_BASE::REG_CL:
			return LYNX_CL;
		case LEVEL_BASE::REG_DL:
			return LYNX_DL;
		case LEVEL_BASE::REG_XMM0:
			return LYNX_XMM0;
		case LEVEL_BASE::REG_XMM1:
			return LYNX_XMM1;
		case LEVEL_BASE::REG_XMM2:
			return LYNX_XMM2;
		case LEVEL_BASE::REG_XMM3:
			return LYNX_XMM3;
		case LEVEL_BASE::REG_XMM4:
			return LYNX_XMM4;
		case LEVEL_BASE::REG_XMM5:
			return LYNX_XMM5;
		case LEVEL_BASE::REG_XMM6:
			return LYNX_XMM6;
		case LEVEL_BASE::REG_XMM7:
			return LYNX_XMM7;
		case LEVEL_BASE::REG_MM0:
			return LYNX_MM0;
		case LEVEL_BASE::REG_MM1:
			return LYNX_MM1;
		case LEVEL_BASE::REG_MM2:
			return LYNX_MM2;
		case LEVEL_BASE::REG_MM3:
			return LYNX_MM3;
		case LEVEL_BASE::REG_MM4:
			return LYNX_MM4;
		case LEVEL_BASE::REG_MM5:
			return LYNX_MM5;
		case LEVEL_BASE::REG_MM6:
			return LYNX_MM6;
		case LEVEL_BASE::REG_MM7:
			return LYNX_MM7;
		case LEVEL_BASE::REG_INVALID_:
			return LYNX_INVALID;
#endif
#ifdef TARGET_IA32E
		case LEVEL_BASE::REG_RIP:
			return LYNX_RIP;
		case LEVEL_BASE::REG_RAX:
			return LYNX_RAX;
		case LEVEL_BASE::REG_RBX:
			return LYNX_RBX;
		case LEVEL_BASE::REG_RCX:
			return LYNX_RCX;
		case LEVEL_BASE::REG_RDX:
			return LYNX_RDX;
		case LEVEL_BASE::REG_RBP:
			return LYNX_RBP;
		case LEVEL_BASE::REG_RSI:
			return LYNX_RSI;
		case LEVEL_BASE::REG_RDI:
			return LYNX_RDI;
		case LEVEL_BASE::REG_RSP:
			return LYNX_RSP;
		case LEVEL_BASE::REG_R8:
			return LYNX_R8;
		case LEVEL_BASE::REG_R9:
			return LYNX_R9;
		case LEVEL_BASE::REG_R10:
			return LYNX_R10;
		case LEVEL_BASE::REG_R11:
			return LYNX_R11;
		case LEVEL_BASE::REG_R12:
			return LYNX_R12;
		case LEVEL_BASE::REG_R13:
			return LYNX_R13;
		case LEVEL_BASE::REG_R14:
			return LYNX_R14;
		case LEVEL_BASE::REG_R15:
			return LYNX_R15;
		case LEVEL_BASE::REG_SEG_CS:
			return LYNX_SEG_CS;
		case LEVEL_BASE::REG_SEG_DS:
			return LYNX_SEG_DS;
		case LEVEL_BASE::REG_SEG_ES:
			return LYNX_SEG_ES;
        case LEVEL_BASE::REG_SEG_FS_BASE:
		case LEVEL_BASE::REG_SEG_FS:
			return LYNX_SEG_FS;
		case LEVEL_BASE::REG_SEG_GS:
			return LYNX_SEG_GS;
		case LEVEL_BASE::REG_SEG_SS:
			return LYNX_SEG_SS;
		case LEVEL_BASE::REG_MXCSR:
			return LYNX_MXCSR;
		case LEVEL_BASE::REG_ST0:
			return LYNX_ST0;
		case LEVEL_BASE::REG_ST1:
			return LYNX_ST1;
		case LEVEL_BASE::REG_ST2:
			return LYNX_ST2;
		case LEVEL_BASE::REG_ST3:
			return LYNX_ST3;
		case LEVEL_BASE::REG_ST4:
			return LYNX_ST4;
		case LEVEL_BASE::REG_ST5:
			return LYNX_ST5;
		case LEVEL_BASE::REG_ST6:
			return LYNX_ST6;
		case LEVEL_BASE::REG_ST7:
			return LYNX_ST7;
		case LEVEL_BASE::REG_FPSW:
			return LYNX_FPSW;
		case LEVEL_BASE::REG_FPCW:
			return LYNX_FPCW;
		#ifdef REG_FPTAG_FULL
		case LEVEL_BASE::REG_FPTAG_FULL:
			return LYNX_FPTAG_FULL;
#endif
			return LYNX_FPTAG_FULL;
		case LEVEL_BASE::REG_FPIP_OFF:
			return LYNX_FPIP_OFF;
		case LEVEL_BASE::REG_FPIP_SEL:
			return LYNX_FPIP_SEL;
		case LEVEL_BASE::REG_FPDP_OFF:
			return LYNX_FPDP_OFF;
		case LEVEL_BASE::REG_FPDP_SEL:
			return LYNX_FPDP_SEL;
		case LEVEL_BASE::REG_FPOPCODE:
			return LYNX_FPOPCODE;
		case LEVEL_BASE::REG_DR0:
			return LYNX_DR0;
		case LEVEL_BASE::REG_DR1:
			return LYNX_DR1;
		case LEVEL_BASE::REG_DR2:
			return LYNX_DR2;
		case LEVEL_BASE::REG_DR3:
			return LYNX_DR3;
		case LEVEL_BASE::REG_DR4:
			return LYNX_DR4;
		case LEVEL_BASE::REG_DR5:
			return LYNX_DR5;
		case LEVEL_BASE::REG_DR6:
			return LYNX_DR6;
		case LEVEL_BASE::REG_DR7:
			return LYNX_DR7;
		case LEVEL_BASE::REG_CR0:
			return LYNX_CR0;
		case LEVEL_BASE::REG_CR1:
			return LYNX_CR1;
		case LEVEL_BASE::REG_CR2:
			return LYNX_CR2;
		case LEVEL_BASE::REG_CR3:
			return LYNX_CR3;
		case LEVEL_BASE::REG_CR4:
			return LYNX_CR4;
		case LEVEL_BASE::REG_GFLAGS:
			return LYNX_GFLAGS;
		case LEVEL_BASE::REG_YMM0:
			return LYNX_YMM0;
		case LEVEL_BASE::REG_YMM1:
			return LYNX_YMM1;
		case LEVEL_BASE::REG_YMM2:
			return LYNX_YMM2;
		case LEVEL_BASE::REG_YMM3:
			return LYNX_YMM3;
		case LEVEL_BASE::REG_YMM4:
			return LYNX_YMM4;
		case LEVEL_BASE::REG_YMM5:
			return LYNX_YMM5;
		case LEVEL_BASE::REG_YMM6:
			return LYNX_YMM6;
		case LEVEL_BASE::REG_YMM7:
			return LYNX_YMM7;
		case LEVEL_BASE::REG_EIP:
			return LYNX_EIP;
		case LEVEL_BASE::REG_EAX:
			return LYNX_EAX;
		case LEVEL_BASE::REG_EBX:
			return LYNX_EBX;
		case LEVEL_BASE::REG_ECX:
			return LYNX_ECX;
		case LEVEL_BASE::REG_EDX:
			return LYNX_EDX;
		case LEVEL_BASE::REG_EBP:
			return LYNX_EBP;
		case LEVEL_BASE::REG_ESI:
			return LYNX_ESI;
		case LEVEL_BASE::REG_EDI:
			return LYNX_EDI;
		case LEVEL_BASE::REG_ESP:
			return LYNX_ESP;
		case LEVEL_BASE::REG_R8D:
			return LYNX_R8D;
		case LEVEL_BASE::REG_R9D:
			return LYNX_R9D;
		case LEVEL_BASE::REG_R10D:
			return LYNX_R10D;
		case LEVEL_BASE::REG_R11D:
			return LYNX_R11D;
		case LEVEL_BASE::REG_R12D:
			return LYNX_R12D;
		case LEVEL_BASE::REG_R13D:
			return LYNX_R13D;
		case LEVEL_BASE::REG_R14D:
			return LYNX_R14D;
		case LEVEL_BASE::REG_R15D:
			return LYNX_R15D;
		case LEVEL_BASE::REG_IP:
			return LYNX_IP;
		case LEVEL_BASE::REG_AX:
			return LYNX_AX;
		case LEVEL_BASE::REG_BX:
			return LYNX_BX;
		case LEVEL_BASE::REG_CX:
			return LYNX_CX;
		case LEVEL_BASE::REG_DX:
			return LYNX_DX;
		case LEVEL_BASE::REG_BP:
			return LYNX_BP;
		case LEVEL_BASE::REG_SI:
			return LYNX_SI;
		case LEVEL_BASE::REG_DI:
			return LYNX_DI;
		case LEVEL_BASE::REG_SP:
			return LYNX_SP;
		case LEVEL_BASE::REG_R8W:
			return LYNX_R8W;
		case LEVEL_BASE::REG_R9W:
			return LYNX_R9W;
		case LEVEL_BASE::REG_R10W:
			return LYNX_R10W;
		case LEVEL_BASE::REG_R11W:
			return LYNX_R11W;
		case LEVEL_BASE::REG_R12W:
			return LYNX_R12W;
		case LEVEL_BASE::REG_R13W:
			return LYNX_R13W;
		case LEVEL_BASE::REG_R14W:
			return LYNX_R14W;
		case LEVEL_BASE::REG_R15W:
			return LYNX_R15W;
		case LEVEL_BASE::REG_AH:
			return LYNX_AH;
		case LEVEL_BASE::REG_BH:
			return LYNX_BH;
		case LEVEL_BASE::REG_CH:
			return LYNX_CH;
		case LEVEL_BASE::REG_DH:
			return LYNX_DH;
		case LEVEL_BASE::REG_AL:
			return LYNX_AL;
		case LEVEL_BASE::REG_BL:
			return LYNX_BL;
		case LEVEL_BASE::REG_CL:
			return LYNX_CL;
		case LEVEL_BASE::REG_DL:
			return LYNX_DL;
		case LEVEL_BASE::REG_BPL:
			return LYNX_BPL;
		case LEVEL_BASE::REG_SIL:
			return LYNX_SIL;
		case LEVEL_BASE::REG_DIL:
			return LYNX_DIL;
		case LEVEL_BASE::REG_SPL:
			return LYNX_SPL;
		case LEVEL_BASE::REG_R8B:
			return LYNX_R8B;
		case LEVEL_BASE::REG_R9B:
			return LYNX_R9B;
		case LEVEL_BASE::REG_R10B:
			return LYNX_R10B;
		case LEVEL_BASE::REG_R11B:
			return LYNX_R11B;
		case LEVEL_BASE::REG_R12B:
			return LYNX_R12B;
		case LEVEL_BASE::REG_R13B:
			return LYNX_R13B;
		case LEVEL_BASE::REG_R14B:
			return LYNX_R14B;
		case LEVEL_BASE::REG_R15B:
			return LYNX_R15B;
		case LEVEL_BASE::REG_YMM8:
			return LYNX_YMM8;
		case LEVEL_BASE::REG_YMM9:
			return LYNX_YMM9;
		case LEVEL_BASE::REG_YMM10:
			return LYNX_YMM10;
		case LEVEL_BASE::REG_YMM11:
			return LYNX_YMM11;
		case LEVEL_BASE::REG_YMM12:
			return LYNX_YMM12;
		case LEVEL_BASE::REG_YMM13:
			return LYNX_YMM13;
		case LEVEL_BASE::REG_YMM14:
			return LYNX_YMM14;
		case LEVEL_BASE::REG_YMM15:
			return LYNX_YMM15;
		case LEVEL_BASE::REG_XMM0:
			return LYNX_XMM0;
		case LEVEL_BASE::REG_XMM1:
			return LYNX_XMM1;
		case LEVEL_BASE::REG_XMM2:
			return LYNX_XMM2;
		case LEVEL_BASE::REG_XMM3:
			return LYNX_XMM3;
		case LEVEL_BASE::REG_XMM4:
			return LYNX_XMM4;
		case LEVEL_BASE::REG_XMM5:
			return LYNX_XMM5;
		case LEVEL_BASE::REG_XMM6:
			return LYNX_XMM6;
		case LEVEL_BASE::REG_XMM7:
			return LYNX_XMM7;
		case LEVEL_BASE::REG_XMM8:
			return LYNX_XMM8;
		case LEVEL_BASE::REG_XMM9:
			return LYNX_XMM9;
		case LEVEL_BASE::REG_XMM10:
			return LYNX_XMM10;
		case LEVEL_BASE::REG_XMM11:
			return LYNX_XMM11;
		case LEVEL_BASE::REG_XMM12:
			return LYNX_XMM12;
		case LEVEL_BASE::REG_XMM13:
			return LYNX_XMM13;
		case LEVEL_BASE::REG_XMM14:
			return LYNX_XMM14;
		case LEVEL_BASE::REG_XMM15:
			return LYNX_XMM15;
		case LEVEL_BASE::REG_MM0:
			return LYNX_MM0;
		case LEVEL_BASE::REG_MM1:
			return LYNX_MM1;
		case LEVEL_BASE::REG_MM2:
			return LYNX_MM2;
		case LEVEL_BASE::REG_MM3:
			return LYNX_MM3;
		case LEVEL_BASE::REG_MM4:
			return LYNX_MM4;
		case LEVEL_BASE::REG_MM5:
			return LYNX_MM5;
		case LEVEL_BASE::REG_MM6:
			return LYNX_MM6;
		case LEVEL_BASE::REG_MM7:
			return LYNX_MM7;
		case LEVEL_BASE::REG_INVALID_:
			return LYNX_INVALID;
#endif
#ifdef TARGET_MIC
		case LEVEL_BASE::REG_ZMM0:
			return LYNX_ZMM0;
		case LEVEL_BASE::REG_ZMM1:
			return LYNX_ZMM1;
		case LEVEL_BASE::REG_ZMM2:
			return LYNX_ZMM2;
		case LEVEL_BASE::REG_ZMM3:
			return LYNX_ZMM3;
		case LEVEL_BASE::REG_ZMM4:
			return LYNX_ZMM4;
		case LEVEL_BASE::REG_ZMM5:
			return LYNX_ZMM5;
		case LEVEL_BASE::REG_ZMM6:
			return LYNX_ZMM6;
		case LEVEL_BASE::REG_ZMM7:
			return LYNX_ZMM7;
		case LEVEL_BASE::REG_ZMM8:
			return LYNX_ZMM8;
		case LEVEL_BASE::REG_ZMM9:
			return LYNX_ZMM9;
		case LEVEL_BASE::REG_ZMM10:
			return LYNX_ZMM10;
		case LEVEL_BASE::REG_ZMM11:
			return LYNX_ZMM11;
		case LEVEL_BASE::REG_ZMM12:
			return LYNX_ZMM12;
		case LEVEL_BASE::REG_ZMM13:
			return LYNX_ZMM13;
		case LEVEL_BASE::REG_ZMM14:
			return LYNX_ZMM14;
		case LEVEL_BASE::REG_ZMM15:
			return LYNX_ZMM15;
		case LEVEL_BASE::REG_ZMM16:
			return LYNX_ZMM16;
		case LEVEL_BASE::REG_ZMM17:
			return LYNX_ZMM17;
		case LEVEL_BASE::REG_ZMM18:
			return LYNX_ZMM18;
		case LEVEL_BASE::REG_ZMM19:
			return LYNX_ZMM19;
		case LEVEL_BASE::REG_ZMM20:
			return LYNX_ZMM20;
		case LEVEL_BASE::REG_ZMM21:
			return LYNX_ZMM21;
		case LEVEL_BASE::REG_ZMM22:
			return LYNX_ZMM22;
		case LEVEL_BASE::REG_ZMM23:
			return LYNX_ZMM23;
		case LEVEL_BASE::REG_ZMM24:
			return LYNX_ZMM24;
		case LEVEL_BASE::REG_ZMM25:
			return LYNX_ZMM25;
		case LEVEL_BASE::REG_ZMM26:
			return LYNX_ZMM26;
		case LEVEL_BASE::REG_ZMM27:
			return LYNX_ZMM27;
		case LEVEL_BASE::REG_ZMM28:
			return LYNX_ZMM28;
		case LEVEL_BASE::REG_ZMM29:
			return LYNX_ZMM29;
		case LEVEL_BASE::REG_ZMM30:
			return LYNX_ZMM30;
		case LEVEL_BASE::REG_ZMM31:
			return LYNX_ZMM31;
		case LEVEL_BASE::REG_K0:
			return LYNX_K0;
		case LEVEL_BASE::REG_K1:
			return LYNX_K1;
		case LEVEL_BASE::REG_K2:
			return LYNX_K2;
		case LEVEL_BASE::REG_K3:
			return LYNX_K3;
		case LEVEL_BASE::REG_K4:
			return LYNX_K4;
		case LEVEL_BASE::REG_K5:
			return LYNX_K5;
		case LEVEL_BASE::REG_K6:
			return LYNX_K6;
		case LEVEL_BASE::REG_K7:
			return LYNX_K7;
		case LEVEL_BASE::REG_RIP:
			return LYNX_RIP;
		case LEVEL_BASE::REG_RAX:
			return LYNX_RAX;
		case LEVEL_BASE::REG_RBX:
			return LYNX_RBX;
		case LEVEL_BASE::REG_RCX:
			return LYNX_RCX;
		case LEVEL_BASE::REG_RDX:
			return LYNX_RDX;
		case LEVEL_BASE::REG_RBP:
			return LYNX_RBP;
		case LEVEL_BASE::REG_RSI:
			return LYNX_RSI;
		case LEVEL_BASE::REG_RDI:
			return LYNX_RDI;
		case LEVEL_BASE::REG_RSP:
			return LYNX_RSP;
		case LEVEL_BASE::REG_R8:
			return LYNX_R8;
		case LEVEL_BASE::REG_R9:
			return LYNX_R9;
		case LEVEL_BASE::REG_R10:
			return LYNX_R10;
		case LEVEL_BASE::REG_R11:
			return LYNX_R11;
		case LEVEL_BASE::REG_R12:
			return LYNX_R12;
		case LEVEL_BASE::REG_R13:
			return LYNX_R13;
		case LEVEL_BASE::REG_R14:
			return LYNX_R14;
		case LEVEL_BASE::REG_R15:
			return LYNX_R15;
		case LEVEL_BASE::REG_SEG_CS:
			return LYNX_SEG_CS;
		case LEVEL_BASE::REG_SEG_DS:
			return LYNX_SEG_DS;
		case LEVEL_BASE::REG_SEG_ES:
			return LYNX_SEG_ES;
        case LEVEL_BASE::REG_SEG_FS_BASE:
		case LEVEL_BASE::REG_SEG_FS:
			return LYNX_SEG_FS;
		case LEVEL_BASE::REG_SEG_GS:
			return LYNX_SEG_GS;
		case LEVEL_BASE::REG_SEG_SS:
			return LYNX_SEG_SS;
		case LEVEL_BASE::REG_MXCSR:
			return LYNX_MXCSR;
		case LEVEL_BASE::REG_ST0:
			return LYNX_ST0;
		case LEVEL_BASE::REG_ST1:
			return LYNX_ST1;
		case LEVEL_BASE::REG_ST2:
			return LYNX_ST2;
		case LEVEL_BASE::REG_ST3:
			return LYNX_ST3;
		case LEVEL_BASE::REG_ST4:
			return LYNX_ST4;
		case LEVEL_BASE::REG_ST5:
			return LYNX_ST5;
		case LEVEL_BASE::REG_ST6:
			return LYNX_ST6;
		case LEVEL_BASE::REG_ST7:
			return LYNX_ST7;
		case LEVEL_BASE::REG_FPSW:
			return LYNX_FPSW;
		case LEVEL_BASE::REG_FPCW:
			return LYNX_FPCW;
		#ifdef REG_FPTAG_FULL
		case LEVEL_BASE::REG_FPTAG_FULL:
			return LYNX_FPTAG_FULL;
#endif
			return LYNX_FPTAG_FULL;
		case LEVEL_BASE::REG_FPIP_OFF:
			return LYNX_FPIP_OFF;
		case LEVEL_BASE::REG_FPIP_SEL:
			return LYNX_FPIP_SEL;
		case LEVEL_BASE::REG_FPDP_OFF:
			return LYNX_FPDP_OFF;
		case LEVEL_BASE::REG_FPDP_SEL:
			return LYNX_FPDP_SEL;
		case LEVEL_BASE::REG_FPOPCODE:
			return LYNX_FPOPCODE;
		case LEVEL_BASE::REG_DR0:
			return LYNX_DR0;
		case LEVEL_BASE::REG_DR1:
			return LYNX_DR1;
		case LEVEL_BASE::REG_DR2:
			return LYNX_DR2;
		case LEVEL_BASE::REG_DR3:
			return LYNX_DR3;
		case LEVEL_BASE::REG_DR4:
			return LYNX_DR4;
		case LEVEL_BASE::REG_DR5:
			return LYNX_DR5;
		case LEVEL_BASE::REG_DR6:
			return LYNX_DR6;
		case LEVEL_BASE::REG_DR7:
			return LYNX_DR7;
		case LEVEL_BASE::REG_CR0:
			return LYNX_CR0;
		case LEVEL_BASE::REG_CR1:
			return LYNX_CR1;
		case LEVEL_BASE::REG_CR2:
			return LYNX_CR2;
		case LEVEL_BASE::REG_CR3:
			return LYNX_CR3;
		case LEVEL_BASE::REG_CR4:
			return LYNX_CR4;
		case LEVEL_BASE::REG_GFLAGS:
			return LYNX_GFLAGS;
		case LEVEL_BASE::REG_YMM0:
			return LYNX_YMM0;
		case LEVEL_BASE::REG_YMM1:
			return LYNX_YMM1;
		case LEVEL_BASE::REG_YMM2:
			return LYNX_YMM2;
		case LEVEL_BASE::REG_YMM3:
			return LYNX_YMM3;
		case LEVEL_BASE::REG_YMM4:
			return LYNX_YMM4;
		case LEVEL_BASE::REG_YMM5:
			return LYNX_YMM5;
		case LEVEL_BASE::REG_YMM6:
			return LYNX_YMM6;
		case LEVEL_BASE::REG_YMM7:
			return LYNX_YMM7;
		case LEVEL_BASE::REG_EIP:
			return LYNX_EIP;
		case LEVEL_BASE::REG_EAX:
			return LYNX_EAX;
		case LEVEL_BASE::REG_EBX:
			return LYNX_EBX;
		case LEVEL_BASE::REG_ECX:
			return LYNX_ECX;
		case LEVEL_BASE::REG_EDX:
			return LYNX_EDX;
		case LEVEL_BASE::REG_EBP:
			return LYNX_EBP;
		case LEVEL_BASE::REG_ESI:
			return LYNX_ESI;
		case LEVEL_BASE::REG_EDI:
			return LYNX_EDI;
		case LEVEL_BASE::REG_ESP:
			return LYNX_ESP;
		case LEVEL_BASE::REG_R8D:
			return LYNX_R8D;
		case LEVEL_BASE::REG_R9D:
			return LYNX_R9D;
		case LEVEL_BASE::REG_R10D:
			return LYNX_R10D;
		case LEVEL_BASE::REG_R11D:
			return LYNX_R11D;
		case LEVEL_BASE::REG_R12D:
			return LYNX_R12D;
		case LEVEL_BASE::REG_R13D:
			return LYNX_R13D;
		case LEVEL_BASE::REG_R14D:
			return LYNX_R14D;
		case LEVEL_BASE::REG_R15D:
			return LYNX_R15D;
		case LEVEL_BASE::REG_IP:
			return LYNX_IP;
		case LEVEL_BASE::REG_AX:
			return LYNX_AX;
		case LEVEL_BASE::REG_BX:
			return LYNX_BX;
		case LEVEL_BASE::REG_CX:
			return LYNX_CX;
		case LEVEL_BASE::REG_DX:
			return LYNX_DX;
		case LEVEL_BASE::REG_BP:
			return LYNX_BP;
		case LEVEL_BASE::REG_SI:
			return LYNX_SI;
		case LEVEL_BASE::REG_DI:
			return LYNX_DI;
		case LEVEL_BASE::REG_SP:
			return LYNX_SP;
		case LEVEL_BASE::REG_R8W:
			return LYNX_R8W;
		case LEVEL_BASE::REG_R9W:
			return LYNX_R9W;
		case LEVEL_BASE::REG_R10W:
			return LYNX_R10W;
		case LEVEL_BASE::REG_R11W:
			return LYNX_R11W;
		case LEVEL_BASE::REG_R12W:
			return LYNX_R12W;
		case LEVEL_BASE::REG_R13W:
			return LYNX_R13W;
		case LEVEL_BASE::REG_R14W:
			return LYNX_R14W;
		case LEVEL_BASE::REG_R15W:
			return LYNX_R15W;
		case LEVEL_BASE::REG_AH:
			return LYNX_AH;
		case LEVEL_BASE::REG_BH:
			return LYNX_BH;
		case LEVEL_BASE::REG_CH:
			return LYNX_CH;
		case LEVEL_BASE::REG_DH:
			return LYNX_DH;
		case LEVEL_BASE::REG_AL:
			return LYNX_AL;
		case LEVEL_BASE::REG_BL:
			return LYNX_BL;
		case LEVEL_BASE::REG_CL:
			return LYNX_CL;
		case LEVEL_BASE::REG_DL:
			return LYNX_DL;
		case LEVEL_BASE::REG_BPL:
			return LYNX_BPL;
		case LEVEL_BASE::REG_SIL:
			return LYNX_SIL;
		case LEVEL_BASE::REG_DIL:
			return LYNX_DIL;
		case LEVEL_BASE::REG_SPL:
			return LYNX_SPL;
		case LEVEL_BASE::REG_R8B:
			return LYNX_R8B;
		case LEVEL_BASE::REG_R9B:
			return LYNX_R9B;
		case LEVEL_BASE::REG_R10B:
			return LYNX_R10B;
		case LEVEL_BASE::REG_R11B:
			return LYNX_R11B;
		case LEVEL_BASE::REG_R12B:
			return LYNX_R12B;
		case LEVEL_BASE::REG_R13B:
			return LYNX_R13B;
		case LEVEL_BASE::REG_R14B:
			return LYNX_R14B;
		case LEVEL_BASE::REG_R15B:
			return LYNX_R15B;
		case LEVEL_BASE::REG_YMM8:
			return LYNX_YMM8;
		case LEVEL_BASE::REG_YMM9:
			return LYNX_YMM9;
		case LEVEL_BASE::REG_YMM10:
			return LYNX_YMM10;
		case LEVEL_BASE::REG_YMM11:
			return LYNX_YMM11;
		case LEVEL_BASE::REG_YMM12:
			return LYNX_YMM12;
		case LEVEL_BASE::REG_YMM13:
			return LYNX_YMM13;
		case LEVEL_BASE::REG_YMM14:
			return LYNX_YMM14;
		case LEVEL_BASE::REG_YMM15:
			return LYNX_YMM15;
		case LEVEL_BASE::REG_YMM16:
			return LYNX_YMM16;
		case LEVEL_BASE::REG_YMM17:
			return LYNX_YMM17;
		case LEVEL_BASE::REG_YMM18:
			return LYNX_YMM18;
		case LEVEL_BASE::REG_YMM19:
			return LYNX_YMM19;
		case LEVEL_BASE::REG_YMM20:
			return LYNX_YMM20;
		case LEVEL_BASE::REG_YMM21:
			return LYNX_YMM21;
		case LEVEL_BASE::REG_YMM22:
			return LYNX_YMM22;
		case LEVEL_BASE::REG_YMM23:
			return LYNX_YMM23;
		case LEVEL_BASE::REG_YMM24:
			return LYNX_YMM24;
		case LEVEL_BASE::REG_YMM25:
			return LYNX_YMM25;
		case LEVEL_BASE::REG_YMM26:
			return LYNX_YMM26;
		case LEVEL_BASE::REG_YMM27:
			return LYNX_YMM27;
		case LEVEL_BASE::REG_YMM28:
			return LYNX_YMM28;
		case LEVEL_BASE::REG_YMM29:
			return LYNX_YMM29;
		case LEVEL_BASE::REG_YMM30:
			return LYNX_YMM30;
		case LEVEL_BASE::REG_YMM31:
			return LYNX_YMM31;
		case LEVEL_BASE::REG_XMM0:
			return LYNX_XMM0;
		case LEVEL_BASE::REG_XMM1:
			return LYNX_XMM1;
		case LEVEL_BASE::REG_XMM2:
			return LYNX_XMM2;
		case LEVEL_BASE::REG_XMM3:
			return LYNX_XMM3;
		case LEVEL_BASE::REG_XMM4:
			return LYNX_XMM4;
		case LEVEL_BASE::REG_XMM5:
			return LYNX_XMM5;
		case LEVEL_BASE::REG_XMM6:
			return LYNX_XMM6;
		case LEVEL_BASE::REG_XMM7:
			return LYNX_XMM7;
		case LEVEL_BASE::REG_XMM8:
			return LYNX_XMM8;
		case LEVEL_BASE::REG_XMM9:
			return LYNX_XMM9;
		case LEVEL_BASE::REG_XMM10:
			return LYNX_XMM10;
		case LEVEL_BASE::REG_XMM11:
			return LYNX_XMM11;
		case LEVEL_BASE::REG_XMM12:
			return LYNX_XMM12;
		case LEVEL_BASE::REG_XMM13:
			return LYNX_XMM13;
		case LEVEL_BASE::REG_XMM14:
			return LYNX_XMM14;
		case LEVEL_BASE::REG_XMM15:
			return LYNX_XMM15;
		case LEVEL_BASE::REG_XMM16:
			return LYNX_XMM16;
		case LEVEL_BASE::REG_XMM17:
			return LYNX_XMM17;
		case LEVEL_BASE::REG_XMM18:
			return LYNX_XMM18;
		case LEVEL_BASE::REG_XMM19:
			return LYNX_XMM19;
		case LEVEL_BASE::REG_XMM20:
			return LYNX_XMM20;
		case LEVEL_BASE::REG_XMM21:
			return LYNX_XMM21;
		case LEVEL_BASE::REG_XMM22:
			return LYNX_XMM22;
		case LEVEL_BASE::REG_XMM23:
			return LYNX_XMM23;
		case LEVEL_BASE::REG_XMM24:
			return LYNX_XMM24;
		case LEVEL_BASE::REG_XMM25:
			return LYNX_XMM25;
		case LEVEL_BASE::REG_XMM26:
			return LYNX_XMM26;
		case LEVEL_BASE::REG_XMM27:
			return LYNX_XMM27;
		case LEVEL_BASE::REG_XMM28:
			return LYNX_XMM28;
		case LEVEL_BASE::REG_XMM29:
			return LYNX_XMM29;
		case LEVEL_BASE::REG_XMM30:
			return LYNX_XMM30;
		case LEVEL_BASE::REG_XMM31:
			return LYNX_XMM31;
		case LEVEL_BASE::REG_MM0:
			return LYNX_MM0;
		case LEVEL_BASE::REG_MM1:
			return LYNX_MM1;
		case LEVEL_BASE::REG_MM2:
			return LYNX_MM2;
		case LEVEL_BASE::REG_MM3:
			return LYNX_MM3;
		case LEVEL_BASE::REG_MM4:
			return LYNX_MM4;
		case LEVEL_BASE::REG_MM5:
			return LYNX_MM5;
		case LEVEL_BASE::REG_MM6:
			return LYNX_MM6;
		case LEVEL_BASE::REG_MM7:
			return LYNX_MM7;
		case LEVEL_BASE::REG_INVALID_:
			return LYNX_INVALID;
#endif
#ifdef TARGET_NONE
		case LEVEL_BASE::REG_FPU_STACK:
			return LYNX_FPU_STACK;
#endif
		default:
			PIN_MutexLock(&errorLock);
			fprintf(errorFile, "Unknown Reg: %d\n", reg);
			PIN_MutexUnlock(&errorLock);
	}
	return LYNX_INVALID;
}
